In [ ]:
import csv
import random
import numpy as np
def read_csv_to_dict(file_path):
    data = []
    with open(file_path, mode='r', encoding='utf-8') as file:
        reader = csv.reader(file)
        for row in reader:
            # 跳过空行

            if not row or row[0] == 'label':
                continue
            # 检查每行是否至少包含两列
            label, content = row[0], row[1]
            data.append({"Label":int(label), "Content": content})

    # random.shuffle(data)
    return data

# 使用方法
file_path = '文本分类练习.csv'  # 替换为实际的文件路径
data_dicts = read_csv_to_dict(file_path)
print(data_dicts)

In [18]:
s = []
for i in data_dicts:
    s.append(i['Label'])
np.unique(s, return_counts=True)

(array([0, 1]), array([7987, 4000]))

In [20]:
7987 - 4000

3987

In [12]:
s = []
for i in data_dicts:
    s.append(len(i['Content']))
np.percentile(s, 95)

69.0

In [25]:
import json
import random

def split_and_save_json(data_list, output_file_80, output_file_20):
    # 随机打乱列表以确保数据的随机性
    # random.shuffle(data_list)
    spi_data_list = data_list[:-3987]
    # 计算分割点
    split_point = int(len(spi_data_list) * 0.8)
    random.shuffle(spi_data_list)
    # 分割数据
    train_data = spi_data_list[:split_point]
    test_data = spi_data_list[split_point:] + data_list[-3987:]

    # 保存数据到JSON文件
    with open(output_file_80, 'w', encoding='utf-8') as f_train:
        json.dump(train_data, f_train, ensure_ascii=False, indent=4)

    with open(output_file_20, 'w', encoding='utf-8') as f_test:
        json.dump(test_data, f_test, ensure_ascii=False, indent=4)

# 假设您已经有了一个字典列表
# 指定输出文件路径
output_file_80 = 'data/train_data.json'
output_file_20 = 'data/test_data.json'

# 调用函数
split_and_save_json(data_dicts, output_file_80, output_file_20)

In [15]:
# -*- coding: utf-8 -*-

import json
import re
import os
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer
"""
数据加载
"""

class DataGenerator2:
    def __init__(self, data_path, config):
        self.config = config
        self.path = data_path
        self.index_to_label = {0: '负向', 1: '正向'}
        self.label_to_index = dict((y, x) for x, y in self.index_to_label.items())
        self.config["class_num"] = len(self.index_to_label)
        if self.config["model_type"] == "bert":
            self.tokenizer = BertTokenizer.from_pretrained(config["pretrain_model_path"])
        self.vocab = load_vocab(config["vocab_path"])
        self.config["vocab_size"] = len(self.vocab)
        self.load()


    def load(self):
        self.data = []
        with open(self.path, encoding="utf8") as f:
            data = json.load(f)
            # print(data)
            for line in data:
   
                label = line["Label"]
                title = line["Content"]
                if self.config["model_type"] == "bert":
                    input_id = self.tokenizer.encode(title, max_length=self.config["max_length"], padding='max_length', truncation=True,)
                else:
                    input_id = self.encode_sentence(title)
                input_id = torch.LongTensor(input_id)
                label_index = torch.LongTensor([label])
                self.data.append([input_id, label_index])
        return

    def encode_sentence(self, text):
        input_id = []
        for char in text:
            input_id.append(self.vocab.get(char, self.vocab["[UNK]"]))
        input_id = self.padding(input_id)
        return input_id

    #补齐或截断输入的序列，使其可以在一个batch内运算
    def padding(self, input_id):
        input_id = input_id[:self.config["max_length"]]
        input_id += [0] * (self.config["max_length"] - len(input_id))
        return input_id

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

def load_vocab(vocab_path):
    token_dict = {}
    with open(vocab_path, encoding="utf8") as f:
        for index, line in enumerate(f):
            token = line.strip()
            token_dict[token] = index + 1  #0留给padding位置，所以从1开始
    return token_dict

def load_json(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = json.load(file)
    return data
#用torch自带的DataLoader类封装数据
def load_data(data_path, config, shuffle=True):
    dg = DataGenerator2(data_path, config)
    dl = DataLoader(dg, batch_size=config["batch_size"], shuffle=shuffle)
    return dl

if __name__ == "__main__":
    from config import Config
    dg = DataGenerator2("data/test_data.json", Config)
    print(dg[1])


[tensor([ 101, 4157,  749, 2523,  719, 2798, 6843, 3341, 8024, 5445,  684, 4157,
        4638, 4156, 6996, 7481, 1789, 4638,  679, 2768, 3416, 2094,  100,  100,
        2345, 6397, 8013,  102,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0]), tensor([0])]


In [26]:
import json
file_path = "data/test_data.json"
with open(file_path, 'r', encoding='utf-8') as file:
    data = json.load(file)
import numpy as np
s = []
for i in data:
    s.append(i['Label'])
np.unique(s, return_counts=True)

(array([0, 1]), array([4776,  811]))

In [27]:
import json
file_path = "data/train_data.json"
with open(file_path, 'r', encoding='utf-8') as file:
    data = json.load(file)
import numpy as np
s = []
for i in data:
    s.append(i['Label'])
np.unique(s, return_counts=True)

(array([0, 1]), array([3211, 3189]))